seed: 42

# run_name: go-ipr-motif
run_name: go-ipr

# ckpt_path: byprot-checkpoints/cfpgen_general_dataset_stage1/checkpoints/last.ckpt
ckpt_path: pretrained/cfpgen_650m/checkpoints/last.ckpt

input_data: data-bin/uniprotKB/cfpgen_general_dataset/test.pkl

# saveto: generation-results/
saveto: generation-results-cfpgen_650m/

num_seqs: 1

seq_lens: [200, 400]  # for general proteins
#seq_lens: [300, 500]  # for enzyme dataset

use_go: true
use_ipr: true
use_ec: false
use_seq_motif: false
motif_min: 10
motif_max: 30

sampling_strategy: gumbel_argmax
max_iter: 100

