_target_: cath

# data_dir: ${data_dir} # data_dir is specified in config.yaml
data_dir: ${paths.data_dir}/cath_4.2

max_length: 500 # 393
atoms: ['N', 'CA', 'C', 'O']

# alphabet related
alphabet:
  name: esm
  featurizer: cath

# dataloader related
max_tokens: 6000
sort: true
num_workers: 8
pin_memory: true
filter_nan: false
