_target_: uniprotKB_if

data_dir: ${paths.data_dir}/uniprotKB/cfpgen_general_dataset

max_length: 1022
atoms: ['N', 'CA', 'C', 'O']

# alphabet related
alphabet:
  name: esm
  featurizer: cath

# dataloader related
max_tokens: 6000
sort: true
num_workers: 8
pin_memory: true
filter_nan: false
